= act(1)

== Name

act - automated configuration tool

== Synopsis

*act* [*-CHMhlpuv*] \[[__user__**@**]_host_]...

== Description

*act* is a tool for automated configuration of remote hosts. It is not
particularly '`smart`' as it attempts to only depend on **rsync**(1),
**sh**(1), and **ssh**(1). (And utilities specified by POSIX-2017.)

Execution of *act* involves two main phases:

1. Copying a set of files to a temporary directory on the remote, specified in
   the file **files-**__hostname__**.list**.
2. Copying a set of executable scripts, referred to as '`modules`', to the
   remote and executing them within the temporary directory. These modules and
   their arguments are specified in the file **modules-**__hostname__**.list**.

Hosts may be specified on the command line. Otherwise, they are read from the
*hosts* file, one per line.

=== File Listing

The file list is passed directly to the *--file-from* argument to *rsync*.
Relative paths in this file are interpreted as relative to the working
directory of *act*.

See the *--files-from* section of the **rsync**(1) manual for further
information.

=== Module Listing

The module list has a simple format:

* Empty lines and comments are ignored.
* All other lines are module invocations, optionally prefixed with *priv:* to
  specify that they should be executed with escalated privileges.
* Comments begin with a '`#`' character and are effective until the end of the
  line.
* Newlines can be escaped by a '`\`' character to break a long line into
  several shorter lines.

Module invocations are similar to shell command invocations. For example, a
module list containing the line

	nop one "two three"

will execute the module '`nop`' with two arguments: '`one`' and '`two three`'.

=== Modules

A '`module`' is a standalone script to be executed on the remote host. There
are several '`builtin`' modules provided with *act* which may serve as
examples. All modules are copied to the *modules* subdirectory of the temporary
directory on the remote host using *rsync* after the file list has been copied.

== Options

*-C* _config-dir_::
Look for file and module lists in _config-dir_ instead of the default *config*.

*-H* _hosts-file_::
Use _hosts-file_ as the hosts file instead of the default *hosts*.

*-M* _module-dir_::
Look for modules in _module-dir_ instead of the default *modules*.

*-h*::
Display help text similar to this section of the manual.

*-l* _log-file_::
Write a log of the execution to _log-file_. Be default, all log output is
written to */dev/null*.

*-p* _method_::
Use _method_ for privilege escalation on the remote host. Currently, the only
accepted values are *doas* and *sudo*.

*-u* _username_::
Use _username_ as the login for the remote host. This name gets passed to
**ssh**(1) via its *-l* option.

*-v*::
Enable verbose output. This also causes the *-v* flag to be passed to *rsync*
and *ACT_VERBOSE* to be set to '`y`' in the environment of each module.

== Environment

*ACT_CONFIG*::
Directory containing file and module lists. Equivalent to using the *-C*
option.

*ACT_HOSTS*::
Host list file. Equivalent to using the *-H* option.

*ACT_MODULES*::
Directory containing modules. Equivalent to using the *-M* option.

*ACT_PRIVESC*::
Privilege escalation method. Acceptable values are *doas* and *sudo*.
Equivalent to using the *-p* option.

*ACT_SSH_USER*::
Set the user login to use when connecting to the remote host. Equivalent to
using the *-u* option.

*ACT_VERBOSE*::
Boolean for enabling verbose output. Equivalent to using the *-v* option.

== Files

*hosts*::
Default host list.

**files-**__hostname__**.list**::
List of files to be copied to _hostname_.

**modules-**__hostname__**.list**::
List of modules to be copied to and executed on _hostname_.

== Notes

=== Rsync

*act* depends on '`real`' *rsync*. That is, the
https://rsync.samba.org[*samba.org*] *rsync*, not *openrsync*. This is mainly
because *openrsync* does not (currently) support the *--files-from* behaviour.
It also dies even when it is only on the receiving end as it doesn't support
*--relative*, which is enabled by *--files-from*.

A simple workaround for this is to use *rsync* instead of *openrsync*. However,
as *openrsync* is part of the OpenBSD base system, *rsync* needs to be
explicitly installed on OpenBSD hosts. A better workaround, only requiring
installation of *rsync* on the local system, is to specify only non-clashing
directories in the file list, as they will be copied recursively without issue,
and edit the *copy_list()* function within *act* as follows:

	 copy_list()
	 {
	 	msg "%s: copying files from list: %s" "${1}" "${2}"
	-	rsync_cmd -r --files-from="${2}" "${PWD}" "${1}:${3}"
	+	rsync_cmd -r --files-from="${2}" --no-relative "${PWD}" "${1}:${3}"
	 	rsync_cmd "${2}" "${1}:${3}"
	 }

If you are running into this issue, it is _strongly_ recommended that you read
the **rsync**(1) manual - specifically the section on *--relative*.

=== Modules

Modules _should_ aim to be idempotent; executing a module more than once with
the same arguments should have the same effect as executing it once.

== See Also

**rsync**(1),
**sh**(1),
**ssh**(1),
**ssh_config**(5)
